/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DonateAndSupportRouteImport } from './routes/DonateAndSupport'
import { Route as CampaignRouteImport } from './routes/Campaign'
import { Route as BlogRouteImport } from './routes/Blog'
import { Route as IndexRouteImport } from './routes/index'

const DonateAndSupportRoute = DonateAndSupportRouteImport.update({
  id: '/DonateAndSupport',
  path: '/DonateAndSupport',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignRoute = CampaignRouteImport.update({
  id: '/Campaign',
  path: '/Campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/Blog',
  path: '/Blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Blog': typeof BlogRoute
  '/Campaign': typeof CampaignRoute
  '/DonateAndSupport': typeof DonateAndSupportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Blog': typeof BlogRoute
  '/Campaign': typeof CampaignRoute
  '/DonateAndSupport': typeof DonateAndSupportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Blog': typeof BlogRoute
  '/Campaign': typeof CampaignRoute
  '/DonateAndSupport': typeof DonateAndSupportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Blog' | '/Campaign' | '/DonateAndSupport'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Blog' | '/Campaign' | '/DonateAndSupport'
  id: '__root__' | '/' | '/Blog' | '/Campaign' | '/DonateAndSupport'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  CampaignRoute: typeof CampaignRoute
  DonateAndSupportRoute: typeof DonateAndSupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/DonateAndSupport': {
      id: '/DonateAndSupport'
      path: '/DonateAndSupport'
      fullPath: '/DonateAndSupport'
      preLoaderRoute: typeof DonateAndSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Campaign': {
      id: '/Campaign'
      path: '/Campaign'
      fullPath: '/Campaign'
      preLoaderRoute: typeof CampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Blog': {
      id: '/Blog'
      path: '/Blog'
      fullPath: '/Blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  CampaignRoute: CampaignRoute,
  DonateAndSupportRoute: DonateAndSupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
